import React, { useState } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  ScrollView, 
  TouchableOpacity,
  SafeAreaView,
  ActivityIndicator,
  Alert,
  Dimensions
} from 'react-native';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import { HealthReportService } from '../../services/healthReports';

const { width } = Dimensions.get('window');

interface AIResponse {
  overallRisk: 'Low' | 'Moderate' | 'High' | 'Urgent';
  confidence: number;
  trend: 'Improving' | 'Stable' | 'Worsening';
  primaryConcern: string;
  riskCategories: {
    category: string;
    riskLevel: 'Low' | 'Moderate' | 'High';
    reason: string;
    recommendedAction: string;
  }[];
  explainableFactors: string[];
  vetUrgency: 'No Immediate Concern' | 'Monitor Closely' | 'Schedule Vet Visit' | 'Visit Vet Soon';
  suggestedActions: string[];
}

// Colors based on risk
const riskColors = {
  Low: '#10B981', // Green
  Moderate: '#F59E0B', // Amber
  High: '#F97316', // Orange
  Urgent: '#EF4444', // Red
};

export default function HealthPredictionScreen({ route, navigation }: any) {
  const { pet, preloadedData } = route.params || {};
  const [isUploading, setIsUploading] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [predictionData, setPredictionData] = useState<AIResponse | null>(preloadedData || null);

  if (!pet) return null;

  const handleLoadDemo = () => {
    setPredictionData({
      overallRisk: "Moderate",
      confidence: 85,
      trend: "Worsening",
      primaryConcern: "Reduced activity and abnormal kidney markers detected in recent blood work.",
      riskCategories: [
        {
          category: "Kidney Health",
          riskLevel: "High",
          reason: "Creatinine levels slightly above normal range.",
          recommendedAction: "Schedule a vet consultation within 3-5 days."
        },
        {
          category: "Weight & Obesity",
          riskLevel: "Moderate",
          reason: "Mild weight gain over the last 3 months.",
          recommendedAction: "Adjust portion sizes slightly."
        },
        {
          category: "Hydration",
          riskLevel: "Low",
          reason: "Water intake appears consistent and normal.",
          recommendedAction: "Maintain current access to fresh water."
        }
      ],
      explainableFactors: [
        "Creatinine level at 1.9 mg/dL (Normal is 0.5-1.5)",
        "30% reduction in daily activity based on logs",
        "Recent weight gain of 1.2 lbs over 14 days"
      ],
      vetUrgency: "Monitor Closely",
      suggestedActions: [
        "Increase water access",
        "Monitor urination frequency",
        "Book a vet consultation",
        "Increase daily walk by 10 mins"
      ]
    });
  };

  const handleUploadReport = async () => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: ['application/pdf', 'image/*'],
        copyToCacheDirectory: true,
      });

      if (result.canceled) return;

      const file = result.assets[0];
      
      setIsUploading(true);
      setPredictionData(null);
      
      // Upload to Supabase
      const uploadRes = await HealthReportService.uploadReport(
        file.uri, 
        pet.id, 
        file.mimeType || 'application/octet-stream',
        file.name
      );

      setIsUploading(false);

      if (!uploadRes.success || !uploadRes.record) {
        Alert.alert("Upload Failed", "Could not save the report to your database. Make sure Supabase is configured.");
        return;
      }

      // Start Analysis
      setIsAnalyzing(true);
      const aiRes = await HealthReportService.generateAIPrediction(
        uploadRes.record.id,
        file.uri,
        file.mimeType || 'application/octet-stream'
      );

      setIsAnalyzing(false);

      if (aiRes.success && aiRes.prediction) {
        try {
          const parsed = JSON.parse(aiRes.prediction);
          setPredictionData(parsed);
        } catch (e) {
          console.error("Failed to parse JSON", e);
          Alert.alert("Analysis Error", "The AI returned an invalid format.");
        }
      } else {
        Alert.alert("Analysis Failed", "Could not generate AI prediction.");
      }

    } catch (error) {
      setIsUploading(false);
      setIsAnalyzing(false);
      console.error(error);
      Alert.alert("Error", "An unexpected error occurred.");
    }
  };

  // Sub-components
  const DisclaimerBanner = () => (
    <View style={styles.disclaimerBanner}>
      <Ionicons name="information-circle" size={20} color="#6366F1" />
      <Text style={styles.disclaimerText}>
        This assessment is generated by AI and is not a veterinary diagnosis. Please consult a licensed veterinarian for medical confirmation.
      </Text>
    </View>
  );

  const OverallStatusCard = ({ data }: { data: AIResponse }) => {
    const color = riskColors[data.overallRisk] || '#64748B';
    
    return (
      <View style={[styles.card, { borderTopWidth: 4, borderTopColor: color }]}>
        <View style={styles.statusHeader}>
          <View>
            <Text style={styles.statusLabel}>Overall Health Status</Text>
            <Text style={[styles.statusValue, { color }]}>{data.overallRisk} Risk</Text>
          </View>
          <View style={[styles.confidenceBadge, { backgroundColor: color + '1A' }]}>
            <Text style={[styles.confidenceText, { color }]}>{data.confidence}% Confidence</Text>
          </View>
        </View>

        <View style={styles.statusDivider} />

        <View style={styles.statusRow}>
          <Text style={styles.statusRowLabel}>Trend:</Text>
          <View style={styles.trendContainer}>
            <Ionicons 
              name={data.trend === 'Improving' ? 'trending-up' : data.trend === 'Worsening' ? 'trending-down' : 'remove'} 
              size={16} 
              color={data.trend === 'Improving' ? '#10B981' : data.trend === 'Worsening' ? '#EF4444' : '#F59E0B'} 
            />
            <Text style={styles.trendText}>{data.trend}</Text>
          </View>
        </View>

        <View style={styles.statusRow}>
          <Text style={styles.statusRowLabel}>Primary Concern:</Text>
          <Text style={styles.concernText} numberOfLines={2}>{data.primaryConcern}</Text>
        </View>
      </View>
    );
  };

  const HealthTrends = () => {
    // Mock data for beautiful animated charts
    const activityData = [40, 60, 50, 80, 70, 90, 85];
    const maxVal = 100;
    const days = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];

    return (
      <View style={styles.card}>
        <Text style={styles.sectionTitle}>Activity Trends (Last 7 Days)</Text>
        <View style={styles.chartContainer}>
          {activityData.map((val, i) => (
            <View key={i} style={styles.barWrapper}>
              <View style={styles.barBg}>
                <View 
                  style={[styles.barFill, { height: `${(val / maxVal) * 100}%`, backgroundColor: val > 60 ? '#38BDF8' : '#94A3B8' }]}
                />
              </View>
              <Text style={styles.barLabel}>{days[i]}</Text>
            </View>
          ))}
        </View>
        <View style={styles.trendFooter}>
          <Text style={styles.trendFooterText}>Improving ↑</Text>
        </View>
      </View>
    );
  };

  const RiskCategories = ({ categories }: { categories: AIResponse['riskCategories'] }) => (
    <View style={styles.categoriesGrid}>
      {categories.map((cat, i) => {
        const color = riskColors[cat.riskLevel] || '#64748B';
        return (
          <View key={i} style={styles.categoryCard}>
            <View style={styles.categoryHeader}>
              <Text style={styles.categoryName} numberOfLines={1}>{cat.category}</Text>
              <View style={[styles.categoryRiskBadge, { backgroundColor: color + '1A' }]}>
                <Text style={[styles.categoryRiskText, { color }]}>{cat.riskLevel}</Text>
              </View>
            </View>
            <Text style={styles.categoryReason} numberOfLines={2}>{cat.reason}</Text>
            <Text style={styles.categoryAction} numberOfLines={2}>Action: {cat.recommendedAction}</Text>
          </View>
        )
      })}
    </View>
  );

  const ExplainableAI = ({ factors }: { factors: string[] }) => (
    <View style={styles.card}>
      <Text style={styles.sectionTitle}>Why did AI generate this risk?</Text>
      <Text style={styles.explainSub}>Factors Influencing Assessment:</Text>
      {factors.map((factor, i) => (
        <View key={i} style={styles.factorRow}>
          <Ionicons name="checkmark-circle" size={20} color="#10B981" />
          <Text style={styles.factorText}>{factor}</Text>
        </View>
      ))}
    </View>
  );

  const VetUrgencyIndicator = ({ urgency }: { urgency: AIResponse['vetUrgency'] }) => {
    let color = '#10B981';
    let icon = 'shield-checkmark';
    if (urgency === 'Monitor Closely') { color = '#F59E0B'; icon = 'eye'; }
    if (urgency === 'Schedule Vet Visit') { color = '#F97316'; icon = 'calendar'; }
    if (urgency === 'Visit Vet Soon') { color = '#EF4444'; icon = 'warning'; }

    return (
      <View style={[styles.urgencyCard, { backgroundColor: color + '1A', borderColor: color + '33' }]}>
        <View style={[styles.urgencyIconBg, { backgroundColor: color }]}>
          <Ionicons name={icon as any} size={24} color="#FFF" />
        </View>
        <View style={styles.urgencyContent}>
          <Text style={styles.urgencyLabel}>Vet Attention Recommendation</Text>
          <Text style={[styles.urgencyValue, { color }]}>{urgency}</Text>
        </View>
      </View>
    );
  };

  const SuggestedActions = ({ actions }: { actions: string[] }) => (
    <View>
      <Text style={[styles.sectionTitle, { paddingHorizontal: 24 }]}>Suggested Actions</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.actionsScroll}>
        {actions.map((action, i) => (
          <TouchableOpacity key={i} style={styles.actionCard}>
            <View style={styles.actionIconBg}>
              <Ionicons name="flash-outline" size={20} color="#D97706" />
            </View>
            <Text style={styles.actionText}>{action}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>
    </View>
  );

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#F8FAFC' }}>
      <ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color="#1E293B" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Health Dashboard</Text>
          <View style={{width: 24}} />
        </View>

        {predictionData && <DisclaimerBanner />}

        <View style={styles.content}>
          
          {!preloadedData && !predictionData && (
            <View style={styles.heroSection}>
              <Text style={styles.title}>{pet.name}'s Health Risk Assessment</Text>
              <Text style={styles.subtitle}>
                Upload a recent vet report, prescription, or lab result to get an AI-powered risk analysis and preventive care steps.
              </Text>

              <TouchableOpacity 
                style={styles.uploadBtn} 
                onPress={handleUploadReport}
                disabled={isUploading || isAnalyzing}
              >
                <Ionicons name="cloud-upload-outline" size={20} color="#FFF" style={{marginRight: 8}} />
                <Text style={styles.uploadBtnText}>Upload New Report</Text>
              </TouchableOpacity>

              <TouchableOpacity 
                style={styles.demoBtn} 
                onPress={handleLoadDemo}
                disabled={isUploading || isAnalyzing}
              >
                <Ionicons name="eye-outline" size={20} color="#38BDF8" style={{marginRight: 8}} />
                <Text style={styles.demoBtnText}>View Demo Dashboard</Text>
              </TouchableOpacity>
            </View>
          )}

          {(isUploading || isAnalyzing) && (
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="large" color="#38BDF8" />
              <Text style={styles.loadingText}>
                {isUploading ? "Uploading to secure vault..." : "AI is analyzing the report..."}
              </Text>
            </View>
          )}

          {predictionData && !isUploading && !isAnalyzing && (
            <View>
              <OverallStatusCard data={predictionData} />
              
              <VetUrgencyIndicator urgency={predictionData.vetUrgency} />

              <HealthTrends />

              <Text style={[styles.sectionTitle, { marginTop: 8 }]}>Risk Categories</Text>
              <RiskCategories categories={predictionData.riskCategories} />

              <ExplainableAI factors={predictionData.explainableFactors} />
            </View>
          )}

        </View>

        {predictionData && !isUploading && !isAnalyzing && (
           <SuggestedActions actions={predictionData.suggestedActions} />
        )}

      </ScrollView>

      {/* Chat FAB */}
      {predictionData && !isUploading && !isAnalyzing && (
        <TouchableOpacity 
          style={styles.chatFab}
          onPress={() => navigation.navigate('AIChat', { pet, predictionData })}
        >
          <Ionicons name="chatbubbles" size={24} color="#FFF" />
          <Text style={styles.chatFabText}>Chat with Vet AI</Text>
        </TouchableOpacity>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingBottom: 60,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: 20,
    marginBottom: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
  },
  disclaimerBanner: {
    flexDirection: 'row',
    backgroundColor: '#EEF2FF',
    marginHorizontal: 24,
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  disclaimerText: {
    flex: 1,
    fontSize: 12,
    color: '#4338CA',
    marginLeft: 8,
    lineHeight: 18,
  },
  content: {
    paddingHorizontal: 24,
  },
  heroSection: {
    marginBottom: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#64748B',
    lineHeight: 22,
    marginBottom: 16,
  },
  uploadBtn: {
    backgroundColor: '#38BDF8',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
    shadowColor: '#38BDF8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  uploadBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
  demoBtn: {
    backgroundColor: '#F0F9FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  demoBtnText: {
    color: '#38BDF8',
    fontSize: 16,
    fontWeight: '700',
  },
  loadingContainer: {
    alignItems: 'center',
    padding: 32,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    marginBottom: 24,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 15,
    color: '#64748B',
    fontWeight: '500',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  statusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  statusLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 4,
  },
  statusValue: {
    fontSize: 24,
    fontWeight: '800',
  },
  confidenceBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  confidenceText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginBottom: 16,
  },
  statusRow: {
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  statusRowLabel: {
    width: 120,
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  trendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  trendText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginLeft: 6,
  },
  concernText: {
    flex: 1,
    fontSize: 14,
    color: '#1E293B',
    fontWeight: '500',
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 16,
  },
  chartContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 150,
    marginBottom: 16,
    paddingTop: 20,
  },
  barWrapper: {
    alignItems: 'center',
    width: 30,
  },
  barBg: {
    height: 100,
    width: 12,
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  barFill: {
    width: 12,
    borderRadius: 6,
  },
  barLabel: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '600',
  },
  trendFooter: {
    alignItems: 'flex-end',
  },
  trendFooterText: {
    fontSize: 13,
    color: '#10B981',
    fontWeight: '700',
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  categoryCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  categoryHeader: {
    marginBottom: 12,
  },
  categoryName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 8,
  },
  categoryRiskBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  categoryRiskText: {
    fontSize: 11,
    fontWeight: '700',
  },
  categoryReason: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 8,
    lineHeight: 18,
  },
  categoryAction: {
    fontSize: 12,
    color: '#38BDF8',
    fontWeight: '600',
  },
  explainSub: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 16,
  },
  factorRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  factorText: {
    flex: 1,
    fontSize: 14,
    color: '#1E293B',
    marginLeft: 12,
    lineHeight: 20,
  },
  urgencyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    marginBottom: 24,
  },
  urgencyIconBg: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  urgencyContent: {
    flex: 1,
  },
  urgencyLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 4,
  },
  urgencyValue: {
    fontSize: 18,
    fontWeight: '800',
  },
  actionsScroll: {
    paddingLeft: 24,
    paddingRight: 8,
  },
  actionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 2,
  },
  actionIconBg: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  actionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
  },
  chatFab: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    backgroundColor: '#6366F1',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 30,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  chatFabText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  }
});
